11

diff --git a/.github/workflows/aws_simple.yml b/.github/workflows/aws_simple.yml
--- a/.github/workflows/aws_simple.yml
+++ b/.github/workflows/aws_simple.yml
@@ -1,9 +1,12 @@
-name: Deploy to AWS Fargate
+name: Deploy to AWS Fargate SIMPLE
 
 on:
   push:
-    branches:
-      - main
+    branches: [main]
+    paths: .github/workflows/aws_simple.yml
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
 
 env:
   AWS_REGION: us-east-1
@@ -34,8 +37,13 @@ jobs:
       # Step 3: Create ECS Cluster (If Not Exists)
       - name: Create ECS Cluster
         run: |
-          aws ecs describe-clusters --clusters ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} || \
-          aws ecs create-cluster --cluster-name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
+          echo "Checking if ECS Cluster '${{ env.CLUSTER_NAME }}' exists..."
+          if ! aws ecs describe-clusters --clusters ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}; then
+            echo "Cluster not found. Creating ECS Cluster '${{ env.CLUSTER_NAME }}'..."
+            aws ecs create-cluster --cluster-name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} || echo "Failed to create cluster"
+          else
+            echo "Cluster '${{ env.CLUSTER_NAME }}' already exists."
+          fi
 
       # Step 6: Replace Tokens in Manifests
       - uses: cschleiden/replace-tokens@v1
